version: '3.3'

services:
  exampleMVC:
    image: mysql:5.7
    container_name: exampleMVC
    environment:
      MYSQL_DATABASE: 'exampleMVC'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
     - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./init/mysql:/var/lib/mysql